name: sumanth_net_admin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^2.0.13
  flutter_email_sender: ^5.1.0
  path_provider: ^2.0.9
  share: ^2.0.4
  pdf: ^3.7.4
  firebase_messaging: ^11.2.15
  googleapis_auth: ^1.3.0
  get_it: ^7.2.0
  permission_handler: ^9.2.0
#  ext_storage: ^1.0.3
  local_auth: ^2.0.0
  logger: ^1.1.0
  flutter_html:
  url_launcher: ^6.1.0
  webview_flutter: ^3.0.2
  firebase_auth: ^3.3.16
  url_launcher_platform_interface: ^2.0.5
  cloud_firestore: ^3.1.13
  firebase_core: ^1.15.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800