name: sumanth_net_admin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  shared_preferences: ^2.0.15
  flutter_email_sender: ^5.1.0
  path_provider: ^2.0.11
  share: ^2.0.4
  pdf: ^3.8.1
  firebase_messaging: ^11.4.4
  googleapis_auth: ^1.3.1
  get_it: ^7.2.0
  printing: ^5.9.1
  permission_handler: ^10.0.0
  local_auth: ^2.1.0
  logger: ^1.1.0
  flutter_html:
  url_launcher: ^6.1.4
  webview_flutter: ^3.0.4
  firebase_auth: ^3.4.1
  url_launcher_platform_interface: ^2.1.0
  cloud_firestore: ^3.2.1
  firebase_core: ^1.19.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter

dev_dependencies:

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800